### ISSUE TITLE
Nullpointer access when colibri is used with specific compositor setup

### ISSUE THREAD

**Issue by edherbert** [darksylinc/colibrigui#50]
Hello. I've stumbled onto what I believe is a potential oversight in Ogre/Colibri. 

In my scenario, I have two compositor workspaces. I render the scene to texture in one, and in the other I render just colibri to the render window. Colibri contains a widget which draws the scene texture. Looks like this:
```
compositor_node renderTextureNode
{
    in 0 renderTexture
    target renderTexture
    {
        pass clear
        {
            colour_value 0 0 0 0
        }
        pass render_scene
        {
        }
    }
}

compositor_node renderWindowNode
{
    in 0 renderWindowTexture
    target renderWindowTexture
    {
        pass clear
        {
            colour_value 0 0 0 0
        }
        pass custom colibri_gui
        {
        }
    }
}

workspace renderTextureWorkspace
{
    connect_output renderTextureNode 0
}

workspace renderWindowWorkspace
{
    connect_output renderWindowNode 0
}

```

If the workspace which renders just colibri is created and executed first (renderWindowWorkspace) then I get the following null pointer exception:
```
#0  0x00007ffff656f0b4 in Ogre::Camera::getNeedsDepthClamp (this=0x0) at /home/edward/build/ogre2/OgreMain/include/OgreCamera.h:758
#1  0x00007ffff656a2b1 in Ogre::Hlms::getPassPsoForScene (this=0x5555572437a0, sceneManager=0x55555728c1e0)
    at /home/edward/build/ogre2/OgreMain/src/OgreHlms.cpp:3192
#2  0x00007ffff6048caf in Ogre::HlmsUnlit::preparePassHash (this=0x5555572437a0, shadowNode=0x0, casterPass=false, 
    dualParaboloid=false, sceneManager=0x55555728c1e0) at /home/edward/build/ogre2/Components/Hlms/Unlit/src/OgreHlmsUnlit.cpp:636
#3  0x00005555561a95e7 in Colibri::ColibriManager::render (this=0x555557237310)
    at /home/edward/build/colibri/src/ColibriGui/ColibriManager.cpp:1670
#4  0x00005555561dde1c in Ogre::CompositorPassColibriGui::execute (this=0x55555746fc60, lodCamera=0x0)
    at /home/edward/build/colibri/src/ColibriGui/Ogre/CompositorPassColibriGui.cpp:51
#5  0x00007ffff69cf0f3 in Ogre::CompositorNode::_update (this=0x555556e80db0, lodCamera=0x0, sceneManager=0x55555728c1e0)
    at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorNode.cpp:820
#6  0x00007ffff69eaed3 in Ogre::CompositorWorkspace::_update (this=0x55555746fa60, bInsideAutoreleasePool=true)
    at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorWorkspace.cpp:838
#7  0x00007ffff69bd536 in Ogre::CompositorManager2::_updateImplementation (this=0x555556ef2bc0)
    at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorManager2.cpp:783
#8  0x00007ffff67655be in Ogre::RenderSystem::updateCompositorManager (this=0x5555569c2870, compositorManager=0x555556ef2bc0)
    at /home/edward/build/ogre2/OgreMain/src/OgreRenderSystem.cpp:1306
#9  0x00007ffff69bd18d in Ogre::CompositorManager2::_update (this=0x555556ef2bc0)
    at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorManager2.cpp:705
#10 0x00007ffff67c4acc in Ogre::Root::_updateAllRenderTargets (this=0x555556a33170)
    at /home/edward/build/ogre2/OgreMain/src/OgreRoot.cpp:1592
#11 0x00007ffff67c239b in Ogre::Root::renderOneFrame (this=0x555556a33170)
    at /home/edward/build/ogre2/OgreMain/src/OgreRoot.cpp:1128
#12 0x0000555555d2982f in AV::Base::update (this=0x7fffffffe590) at /home/edward/Documents/avEngine/src/System/Base.cpp:214
#13 0x00007ffff7d48228 in main (argc=2, argv=0x7fffffffe7b8) at /home/edward/Documents/avEngine/src/Platforms/Main.cpp:60
```
What I've found is that Colibri's hlms expects there to be some camera variables populated (OgreSceneManager::mCamerasInProgress), but these happen as part of the SceneManager compositor node execution. So, if I render the scene to texture first then it works fine as the variable is populated. In my case there is a scenario where I might not want to render the scene at all, i.e starting at the main menu and no gameplay is in progress.

Version: Ogre 2.3.1
Platform reproduced: Arch - OpenGL, MacOS - Metal

**Comment by darksylinc** [comment]
Fixed!

Thanks for the report!
