### ISSUE TITLE
Regression since Multipass support

### ISSUE THREAD

**Issue by edherbert** [darksylinc/colibrigui#58]
Hi. A regression I've noticed since the multipass commit at 776ae508. This happens specifically in a project which does not render any colibri widgets but still runs the pass. I noticed you made a commit to fix a [similar issue](https://github.com/darksylinc/colibrigui/commit/6085babe39a31536037f5bb5a5e5cd69963f28bf), although this occurs for me even with that in place. The backtrace is this:

```
#0  0x00007ffff589f26c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff584fa08 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff5838538 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff5a9ca6f in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff5ab011c in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff5ab0189 in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff5ab03ed in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x5555560ad918 <typeinfo for Ogre::InvalidParametersException>, dest=0x7ffff634170c <Ogre::InvalidParametersException::~InvalidParametersException()>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007ffff62990ff in Ogre::ExceptionFactory::throwException (code=Ogre::Exception::ERR_INVALIDPARAMS, number=2, desc="Mapping 0 bytes is forbidden!", src="BufferPacked::map", 
    file=0x7ffff6d010f0 "/home/edward/build/ogre2/OgreMain/src/Vao/OgreBufferPacked.cpp", line=165) at /home/edward/build/ogre2/OgreMain/include/OgreException.h:284
#8  0x00007ffff68b237b in Ogre::BufferPacked::map (this=0x5555574b50c0, elementStart=0, elementCount=0, bAdvanceFrame=true) at /home/edward/build/ogre2/OgreMain/src/Vao/OgreBufferPacked.cpp:165
#9  0x0000555555c48b8a in Colibri::ColibriManager::render (this=0x555556a2f690) at /home/edward/build/colibri/src/ColibriGui/ColibriManager.cpp:1639
#10 0x0000555555c8fbb5 in Ogre::CompositorPassColibriGui::execute (this=0x555556c4c8e0, lodCamera=0x0) at /home/edward/build/colibri/src/ColibriGui/Ogre/CompositorPassColibriGui.cpp:83
#11 0x00007ffff6854df7 in Ogre::CompositorNode::_update (this=0x555556a350c0, lodCamera=0x0, sceneManager=0x555556a76050) at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorNode.cpp:820
#12 0x00007ffff68715df in Ogre::CompositorWorkspace::_update (this=0x555556c2f6a0, bInsideAutoreleasePool=true) at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorWorkspace.cpp:838
#13 0x00007ffff68425a4 in Ogre::CompositorManager2::_updateImplementation (this=0x555556796c70) at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorManager2.cpp:783
#14 0x00007ffff65d25b2 in Ogre::RenderSystem::updateCompositorManager (this=0x5555565b9900, compositorManager=0x555556796c70) at /home/edward/build/ogre2/OgreMain/src/OgreRenderSystem.cpp:1343
#15 0x00007ffff68421fb in Ogre::CompositorManager2::_update (this=0x555556796c70) at /home/edward/build/ogre2/OgreMain/src/Compositor/OgreCompositorManager2.cpp:705
#16 0x00007ffff6637592 in Ogre::Root::_updateAllRenderTargets (this=0x55555651f3f0) at /home/edward/build/ogre2/OgreMain/src/OgreRoot.cpp:1593
#17 0x00007ffff6634b1f in Ogre::Root::renderOneFrame (this=0x55555651f3f0) at /home/edward/build/ogre2/OgreMain/src/OgreRoot.cpp:1128
#18 0x00007ffff7b381d1 in AV::Base::update (this=0x7fffffffe4e0) at /home/edward/Documents/avEngineOther/src/System/Base.cpp:222
#19 0x00005555558655e0 in main (argc=2, argv=0x7fffffffe718) at /home/edward/Documents/avEngineOther/src/Platforms/Main.cpp:60
```

[getIndirectBuffers](https://github.com/darksylinc/colibrigui/blame/0249c7e4e6c5059e57ef823b9a93017bc880bfe0/src/ColibriGui/ColibriManager.cpp#L213) doesn't seem to perform any checks of whether the number of widgets is greater than 0 which causes Ogre to assert.

**Comment by darksylinc** [comment]
Thanks. [Fixed](https://github.com/darksylinc/colibrigui/commit/ca1bb2faa9f43f6e9580708a536cd5859a49e190).
